///////////////////////////////////////////////////////
//  Write markdown files in the md directory         //
//  Run this file with node  (node server.js)        //
///////////////////////////////////////////////////////

// Import Modules
const fs = require('fs');
const { marked } = require('marked');
const process = require('process');
const config = require('./config.json');
const prettify = require('html-prettify');

function toTitleCase(str) {
    return str.replace(
      /\w\S*/g,
      function(txt) {
        return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
      }
    );
  }
  
function getact() {
    if (process.argv[2] === "-a") {
        return process.argv[3] || "Unknown"
    } else {
        return "Server Mode"
    }
}
// Check if in dev mode
const act = process.argv[2] === "-a" || false
if (act) {
    console.log("GH Pages Mode - No .html extension")
} else {
    console.log("Local Mode - .html extension")
}

// Map MD directory
const farr = fs.readdirSync(config.mdDir)
const pgdt = []
farr.forEach((file, index, arr) => {
    // Tell Terminal which file is being worked on
    console.log("Working on file: " + file + " | " + (index + 1) + " of " + arr.length)
    // Create Path to file
    const pth = config.mdDir + "/" + file
    // Read file
    const md = fs.readFileSync(pth, 'utf8');
    // Convert to HTML
    // Wrap in HTML
    const html = `<!DOCTYPE html>
    <html>
        <head>
            <title> ${config.name} | ${toTitleCase(file.replace(".md", "").replace("_", " "))}</title>
            ${getcss()}
            ${config.customization.head}
        </head>
        <body>
            ${config.customization.pre_content}
            ${prettify(marked.parse(md))}
            ${config.customization.post_content}
            <div class='${config.customization.footer_class} ${file}' id='content-${file}'>
                ${getsrc()}
                ${config.customization.footer}
            </div>
        </body>
    </html>`
    function getcss() {
        if (config.customization.css) {
            // Return CSS if css is true
            return `<link rel="stylesheet" href="${config.customization.css}">`
        } else {
            // Return empty string if css is false
            return ""
        }
    }
    function getsrc() {
        if (config.customization.display_source) {
            // Return source if display_source is true
            return `
                <p>Page Generated by ${getact()} at: ${new Date()}</p>
                <a href="../${config.mdDir + "/" + file}">View Raw Source</a>
                <a href="${config.github}/blob/main/${config.mdDir + "/" + file}">View On Github</a>
                `
        } else {
            // Return date if display_source is false
            return `<p>Page Generated at: ${new Date()}</p>`
        }
    }
    // Write to file (in P directory)
    fs.writeFileSync(config.htmlDir + "/" + file.replace(".md", ".html"), html, "utf8")
    // Tell Terminal which file is finished
    pgdt.push({
        "name": file.replace(".md", "").replace("_", " "),
        "url": config.htmlDir.replace(".","") + "/" + (function () {
            if (act) {
                return file.replace(".md", "")
            } else {
                return file.replace(".md", ".html")
            }
        })(),
    })
    console.log("Finished: " + file + " | " + (index + 1) + " of " + arr.length)
});

// Write pages.json
console.log("Updating Pages Database")
fs.writeFileSync("pages.json", JSON.stringify({ info: config, update: new Date(), pages: pgdt }, null, 4), "utf8")
console.log("Page Database Updated")
console.log("Process Complete")
