###############################################################################
# This is a GH Action workflow file                                           #
# This file Runs automatically when a push is made to the repo                #
# This file is used to build and deploy the site                              #
# This file is used to run the SSR script                                     #              
# This file is used to update the files in the repo                           # 
###############################################################################


name: Update Files
run-name: Run Custom SSR
on: 
  push:
jobs:
  # Build job
  build:
    # This job runs on the latest version of ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
      # Setup the pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      # Run the (Custom) SSR script
      - name: Run SSR
        run: node server.js
      # Build the site with Jekyll, this configures all of the required files
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      # Upload the artifact to the repo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    # Make sure the API token has the required scopes
    permissions:
      contents: read
      pages: write
      id-token: write 
    # Setup GH Pages  
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    # This job runs on the latest version of ubuntu
    runs-on: ubuntu-latest
    # This job runs after the build job
    needs: build
    # Deploy to GH Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
